coxxx/Leads/urls.py
from django.urls import path,include
from Leads.url import lead_urls, leadApi_urls

urlpatterns = [
    path('', include(lead_urls)),
    # path('', include(leadApi_urls)),

]

coxxx/Meetings/urls.py
from django.urls import path
from . import views

app_name='meetings'
urlpatterns = [
    
    path('', views.meetingList, name='meetingList'),
    path('permissions', views.all_permissions, name='permissions'),
    path('<str:lead_id>/addmeeting', views.addMeeting, name='addMeeting'),
    path('<str:lead_id>/meetings', views.meetings, name='meetings'),

]

coxxx/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

coxxx/coxxx/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('Contacts.urls')),
    path('meetings/', include('Meetings.urls')),
    path('leads/', include('Leads.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coxxx/templates/base_lay.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">

  <title>company xxx</title>

  <link rel="stylesheet" href="{% static 'styles.css' %}">


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css">

</head>

<body>

  <div   class="d-flex" id="wrapper">


    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><img src="/static/comany.png" alt="logo" height="30" width="95"></div>
      <div class="list-group list-group-flush">
        <a href="{% url 'leads:createLead'%}" class="list-group-item list-group-item-action bg-light">Add Lead</a>
        <a href="{% url 'leads:leadList'%}" class="list-group-item list-group-item-action bg-light">Leads</a>
        <a href="{% url 'meetings:meetingList'%}" class="list-group-item list-group-item-action bg-light">Meetings</a>
        <a href="{% url 'leads:pdf'%}" class="list-group-item list-group-item-action bg-light">pdf</a>
      </div>
    </div>

    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-outline-primary" id="menu-toggle" data-toggle="tooltip" data-placement="bottom" title="toggler menu"><i class="fa fa-bars"></i></button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            {% if user.is_authenticated%}
            <li class="nav-item mt-2">Welcome, {{request.user.username}} </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout'%}" method="post" class="logout-link">
                  {% csrf_token%}
                  <button class="btn btn-link" type="submit">Logout</button>
              </form>
          </li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
           <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li> 
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container mt-4 col-md-10 offset-md-1 mt-5">
        {% block content %}
        {%endblock%}
      </div>
    </div>


  </div >

  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>
 {% block javascript %}
 {% endblock %}
</body>

</html>

coxxx/templates/base_layout.html
{% load static %}

<html>

<head>
    <title>
        company xyz
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <header class="wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <h1><a class="navbar-brand" href="#!"><img src="/static/comany.png" alt="logo" height="35" width="90"></a>
            </h1>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                </ul>
            </div>

        </nav>
    </header>
    <div class="container col-md-4 offset-md-4 mt-5">
        {% block content%}
        {%endblock%}
    </div>
</body>

</html>

coxxx/templates/filter.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="en">

<head>
    <title></title>
</head>

<body>
    <div class="row">
        <div class="col-md-12" style="display: flex; justify-content: end;">
            <form action="" method="get" class="mr-2 ml-auto" id="filter-form">
                {%render_field filter.form.q class="form-control" onfocus="this.value = this.value;"%}
                {% comment %} {{filter.form|attr:''}} {% endcomment %}
                <button class="btn-outline-primary" id="search">search</button>
            </form>
        </div>
    </div>
</body>
<script>
    var searchField = document.getElementById('id_q');
    var form = document.getElementById('filter-form')
    var searchButton = document.getElementById('search')

    searchField.addEventListener('keyup', () => {
        setTimeout(() => searchButton.click(), 1000)
    })
    searchField.addEventListener('focus', () => {
        var that = this
        setTimeout(function(){ that.selectionStart = that.selectionEnd = 10000; }, 0);
    })
    window.onload = () => {
        searchField.focus()
    }
</script>

</html>

coxxx/templates/home.html
{% load static %}

<html>

<head>
    <title>
        company xyz
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <header class="wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <h1><a class="navbar-brand" href="#!"><img src="/static/comany.png" alt="logo" height="35" width="90"></a>
            </h1>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                </ul>
            </div>

        </nav>
    </header>
    <div class="container col-md-12 offset-md-0 mt-3">
        <img src="/static/call.jpg" class="img-fluid" alt="Responsive image">
    </div>
</body>

</html>