coxxx/Contacts/urls.py
from django.urls import path
from . import views

app_name='contacts'
urlpatterns = [
     path('<str:lead_id>/addcontact', views.addContact, name='addContact'),
     path('<str:lead_id>/contacts', views.contacts, name='contacts'),
]

coxxx/Leads/urls.py
from django.urls import path,include
from Leads.url import lead_urls, leadApi_urls

urlpatterns = [
    path('', include(lead_urls)),
    # path('', include(leadApi_urls)),

]

coxxx/Meetings/urls.py
from django.urls import path
from . import views

app_name='meetings'
urlpatterns = [
    
    path('', views.meetingList, name='meetingList'),
    path('permissions', views.all_permissions, name='permissions'),
    path('<str:lead_id>/addmeeting', views.addMeeting, name='addMeeting'),
    path('<str:lead_id>/meetings', views.meetings, name='meetings'),

]

coxxx/coxxx/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('Contacts.urls')),
    path('meetings/', include('Meetings.urls')),
    path('leads/', include('Leads.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coxxx/Leads/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Lead(models.Model):
    name = models.CharField(max_length=100, default="", blank=False, null= False)
    creator = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    description = models.TextField(default="")
    class stageChoice(models.TextChoices):
        Lead = 'lead', _('Lead')
        Potential = 'potential', _('Potential')
        Opportunity = 'opportunity', _('Opportunity')
        Customer = 'customer', _('Customer')


    stage = models.CharField(
        max_length=100,
        choices=stageChoice.choices,
        default=stageChoice.Lead,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('leadDetail', args=[str(self.id)])


         

coxxx/Leads/forms.py
from django import forms
from . import models


def is_anagram(x, y):
    return sorted(x) == sorted(y)


class CreateLead(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'add the lead name'})
    )

    class Meta:
        model = models.Lead
        fields = ['name', 'stage', 'description']

        widgets = {
            #  'name':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'add the lead name'}),
            'stage': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'rows': 3, 'class': 'form-control', 'placeholder': 'please add the description'}),

        }

    def clean_name(self):
        data = self.cleaned_data.get('name')
        if len(data) < 3:
            raise forms.ValidationError(
                'lead name has to be greater than 3 characters ')
        return data

coxxx/Leads/views.py
from .utils import render_to_pdf
from django.views.generic import View
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponse
from .models import Lead
from Contacts.models import Contact
from Meetings.models import Meeting
from . import forms
from .forms import CreateLead
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .filters import leadFilter
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import LeadSerializer
from background_task import background
from django.conf import settings
import schedule
import time
import json
import urllib
from django.core import serializers
from django.core.serializers import serialize
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core.paginator import Paginator
from django.views.generic import View, ListView, UpdateView, CreateView, DeleteView, DetailView
import datetime

leads_url = 'leads:leadList'
create_lead_template = 'leads/createLead.html'


def generate_pdf(request, *args, **kwargs):
    data = {
        'today': datetime.date.today(),
        'amount': 39.99,
        'customer_name': 'Tusifu Edison',
        'order_id': 1233434,
    }
    pdf = render_to_pdf('leads/report.html', data)
    return HttpResponse(pdf, content_type='application/pdf')

# Create your views here.
# @login_required(login_url="/accounts/login/")
# def leadList(request):
#     leads = Lead.objects.all()
#     myFilter = leadFilter(request.GET, queryset=leads)
#     leads = myFilter.qs
#     return render(request, 'leads/leadList.html', {'leads':leads})


class leadList(ListView):
    model = Lead
    template_name = 'leads/leadList.html'
    paginate_by = 3
    context_object_name = 'leads'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = leadFilter(
            self.request.GET, queryset=Lead.objects.all())
        return context

    def get_queryset(self):
        return leadFilter(self.request.GET, queryset=Lead.objects.all()).qs


# Class for creating the new Lead

class CreateLeadClass(CreateView):
    model = Lead
    template_name = create_lead_template
    form_class = CreateLead

    def form_valid(self, form):
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())

        if result['success']:
            instance = form.save(commit=False)
            instance.creator = self.request.user
            instance.save()
            messages.success(self.request, 'lead successfully added')

            return redirect(leads_url)
        else:
            messages.error(self.request, 'invalid reCaptcha please try again')
            return redirect('leads:createLead')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['head'] = 'Create'
        return context


class UpdateLeadClass(UpdateView):
    model = Lead
    template_name = create_lead_template
    form_class = CreateLead

    def form_valid(self, form):
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())

        if result['success']:
            instance = form.save(commit=False)
            instance.creator = self.request.user
            instance.save()
            messages.success(self.request, 'lead successfully added')

            return redirect(leads_url)
        else:
            messages.error(self.request, 'invalid reCaptcha please try again')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['head'] = 'update'
        return context


# @login_required(login_url="/accounts/login/")
# def createLead (request):
#     head='add '
#     if request.method == 'POST':
#         form = forms.CreateLead(request.POST)
#         if form.is_valid():

#             recaptcha_response = request.POST.get('g-recaptcha-response')
#             url = 'https://www.google.com/recaptcha/api/siteverify'
#             values = {
#                 'secret' : settings.GOOGLE_RECAPTCHA_SECRET_KEY,
#                 'response' : recaptcha_response
#             }
#             data = urllib.parse.urlencode(values).encode()
#             req = urllib.request.Request(url, data = data)
#             response = urllib.request.urlopen(req)
#             result = json.loads(response.read().decode())


#             if result['success']:
#                 instance = form.save(commit=False)
#                 instance.creator = request.user
#                 instance.save()
#                 messages.success(request, 'lead successfully added')

#                 return redirect(leads_url)
#             else:
#                 messages.error(request, 'invalid reCaptcha please try again')

#         else:
#             messages.warning(request, 'error occured')
#             return redirect('leads:createLead')
#     else:
#          form = forms.CreateLead()
#     return render(request, create_lead_template, {'form':form,'head':head})

@login_required(login_url="/accounts/login/")
def leadDetail(request, lead_id):
    lead = Lead.objects.get(pk=lead_id)
    contacts = Contact.objects.all().filter(lead__id=lead.id)
    meetings = Meeting.objects.all().filter(lead__id=lead.id)
    return render(request, 'leads/leadDetail.html', {'lead': lead, 'contacts': contacts, 'meetings': meetings})


@login_required(login_url="/accounts/login/")
def deleteLead(request, lead_id):
    lead = Lead.objects.get(pk=lead_id)
    lead.delete()
    return redirect(leads_url)


@login_required(login_url="/accounts/login/")
def updateLead(request, lead_id):
    head = 'update'
    lead = Lead.objects.get(pk=lead_id)
    form = forms.CreateLead(request.POST or None, instance=lead)
    if form.is_valid():
        form.save()
        return redirect(leads_url)
    return render(request, create_lead_template, {'form': form, 'head': head})


@api_view(['GET'])
def leads_api(request):
    leads = Lead.objects.all()
    serializer = LeadSerializer(leads, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def lead_api(request, lead_id):
    leads = Lead.objects.get(pk=lead_id)
    serializer = LeadSerializer(leads, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def leadCreate_api(request):
    form = LeadSerializer(data=request.data)
    if form.is_valid():
        form.save()
    return Response(form.data)


@api_view(['POST'])
def leadUpdate_api(request, lead_id):
    lead = Lead.objects.get(pk=lead_id)
    form = LeadSerializer(instance=lead, data=request.data)
    if form.is_valid():
        form.save()
    return Response(form.data)


@background(schedule=60)
@api_view(['DELETE'])
def leadDelete_api(request, lead_id):
    lead = Lead.objects.get(pk=lead_id).toJSON()
    lead.delete()
    return Response('the lead deleted successfully')

coxxx/Leads/templates/leads/createLead.html
{% extends 'base_lay.html'%}
{% block javascript %}
<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
    $("input[name=anonymous]:radio").click(function (ev) {
        if (ev.currentTarget.value == "no") {
            $('#test').addClass('d-none');
        }
        else if (ev.currentTarget.value == "yes") {
            $('#test').removeClass('d-none');
        }
    });
</script>
{% endblock %}

{% block content%}
{% comment %} <div class="wrapper">
    <div class="card row shadow p-3">
        <div class="h1">
            <h2 class="mb-4">{{head}} a Lead</h2>
        </div>
        <form action="" method="post">
            {% csrf_token%}
            {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}" class="label"> {{ field.html_name}}:</label>
                {{field}}
                {% for error in field.errors %}
                <p class="help is-danger"> {{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}
            <br>



            <input type="submit" value="Submit" class="btn btn-primary mt-4 mb-4">
        </form> {% endcomment %}

        {{ form.non_field_errors }}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{message.tags}}">{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="" method="post" class="form-group">
            {% csrf_token%}
            <input type="radio" name="anonymous" id="yes" value="yes">
            <label for="showLead">show lead name and stage</label>
            <input type="radio" name="anonymous" id="no" value="no">
            <label for="showLead">don't show lead name and stage</label>
            

                <div id="test">
                    <div class="row">
                    <div class="col-md-6">
                        <label for="{{ form.name.id_for_label }}">lead name :</label>
                        {{form.name}}
                        {% for error in form.name.errors %}
                        <p class="text-danger"> {{error}}</p>
                        {% endfor %}
                    </div>
                    <div class="col-md-6">
                        <label for="{{ form.name.id_for_label }}">stage :</label>
                        {{form.stage}}
                    </div>
                </div>

                </div>





            
            <div class="row mt-3">
                <div class="col-md-12">
                    {{ form.description.label_tag }}
                    {{form.description}}
                </div>
            </div>
            <div class="g-recaptcha" data-sitekey="6LfQKKYZAAAAAO8oWrjK3GtqNZUVhNFeMjqUopR3"></div>
            <input type="submit" value="Submit" class="btn btn-primary mt-4">
        </form>

    </div>
</div>
{% endblock %}

coxxx/Leads/templates/leads/leadDetail.html
{% extends 'base_lay.html'%}

{% block content%}
<div class="header">
    <h2>{{lead.name}} Detail page</h2>
</div>
<div>

    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><b>Information</b></h5>
                    <p class="card-text"><b>lead title: </b>{{lead.name}}</p>
                    <p class="card-text"><b>lead stage: </b>{{lead.stage}}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body" style="height: 140px;">
                    <h5 class="card-title"><b>Primary contacts</b></h5>
                    {% if contacts %}
                    {% for contact in contacts%}
                    {% if contact.isPrimary == True%}
                    <p class="card-text"><b>email: </b>{{contact.email}}</p>
                    <p class="card-text"><b>phone: </b>{{contact.phone}}</p>
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    <p class="card-text"><b>No Contacts for this lead</b></p>
                    <p class="card-text"><b></b></p>
 
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card card-body">
                <a href="{% url 'meetings:addMeeting' lead_id=lead.id%}" class="btn btn-outline-primary mt-2">add
                    meeting <i class="fa fa-plus"></i></a>
                <a href="{% url 'meetings:meetings' lead_id=lead.id%}" class="btn btn-outline-primary mt-2">meetings
                    <i class="fa fa-meetup"></i>
                </a>
                
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-body">
                <a href="{% url 'contacts:addContact' lead_id=lead.id%}" class="btn btn-outline-primary mt-2">add
                    contact <i class="fa fa-plus"></i></a>
                <a href="{% url 'contacts:contacts' lead_id=lead.id%}" class="btn btn-outline-primary mt-2">contacts
                    <i class="fa fa-phone"></i>
                </a>
            </div>
        </div>
    </div>


</div>
{% endblock%}

coxxx/Leads/templates/leads/leadList.html
{% extends 'base_lay.html'%}

{% block content%}
<div class="section">
    <div class="h1">
        <h1>Leads</h1>
    </div>
    <div>
    {% include 'filter.html' %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Lead title</th>
                    <th>stage</th>
                    <th>description</th>
                    <th>Detail</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                {% for lead in leads %}
                <tr>
                    <td>{{lead.id}}</td>
                    <td>{{ lead.name }}</td>
                    <td>{{ lead.stage }}</td>
                    <td>{{ lead.description}}</td>
                    <td><a href="{% url 'leads:leadDetail' lead_id=lead.id %}">detail</a></td>
                    <td><a href="{% url 'leads:delete' lead_id=lead.id %}" class="btn btn-outline-danger"
                            data-toggle="tooltip" data-placement="bottom" title="delete"><i class="fa fa-trash"></i></a>
                        <a href="{% url 'leads:update' lead_id=lead.id %}" class="btn btn-outline-success"
                            data-toggle="tooltip" data-placement="bottom" title="update"><i class="fa fa-edit"></i></a>
                    </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock %}

coxxx/Leads/templates/leads/report.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
    {% load static %}
<head>
    <title>Report</title>
    <style type="text/css">
        body {
            font-weight: 200;
            font-size: 14px;
        }
        
        .header {
            font-size: 20px;
            font-weight: 100;
            text-align: center;
            color: #0E5F8B;
        }
        
        .title {
            font-size: 22px;
            font-weight: 100;
            /* text-align: right;*/
            padding: 10px 20px 0px 20px;
        }
        
        .title span {
            color: #007cae;
        }
        
        .details {
            padding: 10px 20px 0px 20px;
            text-align: left !important;
            /*margin-left: 40%;*/
        }
        
        .hrItem {
            border: none;
            height: 1px;
            /* Set the hr color */
            color: #0E5F8B;
            /* old IE */
            background-color: #fff;
            /* Modern Browsers */
        }
        
        .content-table {
            border-collapse: collapse;
            margin: 12px 0;
            font-size: 1rem;
            min-width: 400px;
            width: -webkit-fill-available;
        }
        
        th,
        td {
            padding: 4px 18px;
        }
        
        tbody tr {
            border-bottom: #dddddd;
        }
        
        tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }
        
        thead tr {
            background-color: #0E5F8B;
            color: white;
            text-align: left;
        }
        
        img {
            zoom: 80%;
        }
    </style>
</head>

<body>


    <img src="/Users/edisontusifu/Desktop/edison/coxxx/assets/Header_Image.png" alt="logo">
<!-- <img src="media/Header_Imange.png" alt="logo"> -->

    <div class='header'>
        <p class='title'>Report # {{order_id}}</p>
    </div>
    <div>
        <div class='details'>
            Reporter: {{customer_name}}<br/> Amount: {{amount}} <br/> Date: {{today}}
            <hr class='hrItem' />
        </div>
    </div>
    <div class="content">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen recently
            with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

    </div>
    <table class="content-table">
        <caption>Leads Table</caption>
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Final</th>
                <th scope="col">Occurance Date</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>First</td>
                <td>Male</td>
                <td>Yes</td>
                <td>12/12/2020</td>
            </tr>
            <tr>
                <td>Second</td>
                <td>Male</td>
                <td>Yes</td>
                <td>12/12/2020</td>
            </tr>
        </tbody>
    </table>

    <h3>Test Flex</h3>
    <table>
        <tbody>
            <tr>
                <td>

                </td>
                <td>
                    Lorem Ipsum fact that a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop
                    (injected humour and the like).
                </td>
            </tr>
            <tr>
                <td>
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here,
                </td>
                <td>

                </td>
            </tr>
        </tbody>
    </table>
</body>

</html>